/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const NButton: typeof import('naive-ui')['NButton']
  const NDate: typeof import('naive-ui')['NDate']
  const NSpace: typeof import('naive-ui')['NSpace']
  const NTime: typeof import('naive-ui')['NTime']
}
