services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: reviveit-backend
    container_name: reviveit-backend
    restart: "always"
    env_file:
      - ./backend/.env
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: reviveit-frontend
    container_name: reviveit-frontend
    restart: "always"
    ports:
      - "80:80"
    environment:
      - API_URL=http://backend
    depends_on:
      - backend
    networks:
      - internal

networks:
  internal:
    driver: bridge