services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: reviveit-backend
    container_name: reviveit-backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=reviveit_server.settings
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/database:/app/database
    command: >
      sh -c "python manage.py migrate &&
            python manage.py createsuperuser --noinput --username $DJANGO_SUPERUSER_USERNAME &&
            python manage.py runserver 0.0.0.0:8000"
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: reviveit-frontend
    container_name: reviveit-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - internal

networks:
  internal:
    driver: bridge